table 'Fact Revenue'
	lineageTag: c87753fc-ceff-4f59-9055-f6b49fbc0c30

	column revenue_sk
		dataType: string
		lineageTag: fa780e28-9fbc-4c13-9916-8c4919e946c9
		summarizeBy: none
		sourceColumn: revenue_sk

		annotation SummarizationSetBy = Automatic

	column opportunity_sk
		dataType: string
		lineageTag: c2ccd2fe-27c0-4a90-b344-0d0752c92178
		summarizeBy: none
		sourceColumn: opportunity_sk

		annotation SummarizationSetBy = Automatic

	column user_sk
		dataType: string
		lineageTag: 182a1e08-fb79-4404-8394-5350859c2c2c
		summarizeBy: none
		sourceColumn: user_sk

		annotation SummarizationSetBy = Automatic

	column brand_sk
		dataType: string
		lineageTag: ff64c9ce-774b-4af8-a857-912a53436b92
		summarizeBy: none
		sourceColumn: brand_sk

		annotation SummarizationSetBy = Automatic

	column calendar_sk
		dataType: string
		lineageTag: d6291bc6-cd73-4da2-9a9f-ff5a03dae770
		summarizeBy: none
		sourceColumn: calendar_sk

		annotation SummarizationSetBy = Automatic

	column opportunity_stage_sk
		dataType: string
		lineageTag: 52a7c040-7dc7-46fe-935a-809491bea419
		summarizeBy: none
		sourceColumn: opportunity_stage_sk

		annotation SummarizationSetBy = Automatic

	column negotiation_type_sk
		dataType: string
		lineageTag: c68f0a6a-b956-4b70-a259-1e728fb68e90
		summarizeBy: none
		sourceColumn: negotiation_type_sk

		annotation SummarizationSetBy = Automatic

	column revenue_hierarchy_sk
		dataType: string
		lineageTag: 8ba5a61f-f85c-439a-ab1c-15f43f05d656
		summarizeBy: none
		sourceColumn: revenue_hierarchy_sk

		annotation SummarizationSetBy = Automatic

	column revenue_value
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 1b2f7867-28e3-49ed-bd25-9f5524470345
		summarizeBy: sum
		sourceColumn: revenue_value

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition 'Fact Revenue' = m
		mode: import
		source =
				let
				  Origem = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lZZLTgMxEETvkjWR3NW2Z2YJCIkFAhQ+G8T9r0ESTS3aM3GZnZVET61KvbZ/fg6np+9jSna4O7y9r4evj/XwcFoPj/cvRyTUY8Lx+sHH5/kbPx9eP9efnJ7Xg6GklA6/d2SDbJANsqHZIPtyWKaIdqJdjO17aCc6nw9zM3UmOhPt+1P30eWSiKXILmSXTSIe2Fmn7c3cley6mXuAHdI2myN7InvqxV3OYDn3goieiZ57JbmFDmNPHtEL0UsvkXKjf6EkSwzE0oq+HnqBaG3m2BGjkWYikN3+xf8xxY4YjTSIRHS3G22MRlrXyDJS7UZ2o5GWRSK62e3UFNKKCKTIipjFZhuFtCoS2WXHRGKzjT7aJBKpuiNo+kchbRaR7LJDR1prKKQtIpHp35cNaCSSiGSX3WgTIwGVhIlIZt2SZm2DSgIik112zKRpIOgkXGSy6ExyMzelxPaadM2O12SzpkArUXqZ1JHrpr2CQStRe5ncYsdHSTM2rcTUi6QOLRNEdUArMYtI9DIxi/sV1BKLiGRgm+RYQaeWnkQmepsYamRTS1dv14F1UmJNnFq6ersOrBNvMqGW7iKTgXVSGza19CwyGVgnOd46Ti19+3qNmQyskym649TS1et1YJ2s/+XvHw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [revenue_sk = _t, opportunity_sk = _t, user_sk = _t, brand_sk = _t, calendar_sk = _t, opportunity_stage_sk = _t, negotiation_type_sk = _t, revenue_hierarchy_sk = _t, revenue_value = _t]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Origem, {{"revenue_sk", type text}, {"opportunity_sk", type text}, {"user_sk", type text}, {"brand_sk", type text}, {"calendar_sk", type text}, {"opportunity_stage_sk", type text}, {"negotiation_type_sk", type text}, {"revenue_hierarchy_sk", type text}, {"revenue_value", Int64.Type}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_ResultType = Table

